// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjiIctHac8lxOfb97KlkWWTW051k2gi4',
    appId: '1:1055121686996:web:4d20f0269f04c5a3e89641',
    messagingSenderId: '1055121686996',
    projectId: 'goalplay-bcd21',
    authDomain: 'goalplay-bcd21.firebaseapp.com',
    storageBucket: 'goalplay-bcd21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADfXsPl6FZWdy6WnbnyDi28JFs8gP3ODg',
    appId: '1:1055121686996:android:05306f5e6106aeb5e89641',
    messagingSenderId: '1055121686996',
    projectId: 'goalplay-bcd21',
    storageBucket: 'goalplay-bcd21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkMWXo653KDhJlLQQN-c8Auw4Qjx6u__Y',
    appId: '1:1055121686996:ios:3aa63c11fd5c78c6e89641',
    messagingSenderId: '1055121686996',
    projectId: 'goalplay-bcd21',
    storageBucket: 'goalplay-bcd21.firebasestorage.app',
    iosClientId: '1055121686996-gab0f225dbfin6tgnau44s4ekp097li0.apps.googleusercontent.com',
    iosBundleId: 'com.example.realLifeRpg',
  );
}
